defaults:
  - dataset: nab

common:
  seed: 200
  max_initial_steps: 50
  max_steps: 500
  batch_size: 16
  patience: 150
  lr: 1e-3
  hidden_size: 256
  run_dir: ./experiment

dataset:
  nab:
    dataset_name: NAB
    window_size: 10
    run_dir: ${common.run_dir}/nab

  air_quality:
    dataset_name: AirQuality
    window_size: 24
    run_dir: ${common.run_dir}/airQuality
